spring:
  application:
    name: payments-processor

app:
  timezone: Asia/Kolkata

server:
  port: 8085

# PayPal details
paypal:
  client-id: ${paypal-client-id}
  client-secret: ${paypal-client-secret}
  client-mode: sandbox
